export const locations = {
    0: [
      { name: 'São Paulo', country: 'Brazil', records: 100 },
      { name: 'Buenos Aires', country: 'Argentina', records: 60 },
      { name: 'Rio de Janeiro', country: 'Brazil', records: 70 },
      { name: 'Lima', country: 'Peru', records: 55 },
      { name: 'Bogotá', country: 'Colombia', records: 90 },
      { name: 'Santiago', country: 'Chile', records: 85 },
      { name: 'Caracas', country: 'Venezuela', records: 65 },
      { name: 'Quito', country: 'Ecuador', records: 50 },
      { name: 'Montevideo', country: 'Uruguay', records: 40 },
      { name: 'Asunción', country: 'Paraguay', records: 35 },
      { name: 'La Paz', country: 'Bolivia', records: 30 },
      { name: 'Medellín', country: 'Colombia', records: 45 },
      { name: 'Cali', country: 'Colombia', records: 40 },
      { name: 'Maracaibo', country: 'Venezuela', records: 35 },
      { name: 'Valparaíso', country: 'Chile', records: 25 },
      { name: 'Rosario', country: 'Argentina', records: 33 },
      { name: 'Salvador', country: 'Brazil', records: 60 },
      { name: 'Guayaquil', country: 'Ecuador', records: 55 },
      { name: 'Mendoza', country: 'Argentina', records: 30 },
      { name: 'Fortaleza', country: 'Brazil', records: 50 },
      { name: 'Cusco', country: 'Peru', records: 20 },
      { name: 'Manaus', country: 'Brazil', records: 40 },
      { name: 'Recife', country: 'Brazil', records: 65 },
      { name: 'Barranquilla', country: 'Colombia', records: 37 },
      { name: 'Barquisimeto', country: 'Venezuela', records: 28 },
      { name: 'Temuco', country: 'Chile', records: 23 },
      { name: 'Posadas', country: 'Argentina', records: 18 },
      { name: 'Arequipa', country: 'Peru', records: 22 },
      { name: 'San Cristóbal', country: 'Venezuela', records: 19 },
      { name: 'Cochabamba', country: 'Bolivia', records: 26 },
      { name: 'Tucumán', country: 'Argentina', records: 29 },
      { name: 'João Pessoa', country: 'Brazil', records: 21 },
      { name: 'Natal', country: 'Brazil', records: 22 },
      { name: 'Santa Cruz', country: 'Bolivia', records: 30 },
      { name: 'Cartagena', country: 'Colombia', records: 32 },
      { name: 'Santa Marta', country: 'Colombia', records: 24 },
      { name: 'Iquitos', country: 'Peru', records: 18 },
      { name: 'Neuquén', country: 'Argentina', records: 20 },
      { name: 'Antofagasta', country: 'Chile', records: 25 },
      { name: 'Arica', country: 'Chile', records: 15 },
      { name: 'Punta Arenas', country: 'Chile', records: 12 },
      { name: 'Pucallpa', country: 'Peru', records: 16 },
      { name: 'Trujillo', country: 'Peru', records: 30 },
      { name: 'Rancagua', country: 'Chile', records: 14 },
      { name: 'Ribeirão Preto', country: 'Brazil', records: 28 },
      { name: 'Maceió', country: 'Brazil', records: 25 },
      { name: 'Belém', country: 'Brazil', records: 40 },
      { name: 'Porto Alegre', country: 'Brazil', records: 35 },
      { name: 'Talcahuano', country: 'Chile', records: 20 },
      { name: 'Concepción', country: 'Chile', records: 22 },
      { name: 'Campinas', country: 'Brazil', records: 32 }
    ],
    1: [
        { name: 'Silicon Valley', records: 120 },
        { name: 'Toronto', records: 90 },
        { name: 'Seattle', records: 70 },
        { name: 'New York City', records: 150 },
        { name: 'Los Angeles', records: 130 },
        { name: 'Chicago', records: 110 },
        { name: 'Houston', records: 95 },
        { name: 'Dallas', records: 88 },
        { name: 'Miami', records: 85 },
        { name: 'San Francisco', records: 105 },
        { name: 'Boston', records: 92 },
        { name: 'Atlanta', records: 84 },
        { name: 'Washington D.C.', records: 115 },
        { name: 'Denver', records: 80 },
        { name: 'Vancouver', records: 78 },
        { name: 'Montreal', records: 82 },
        { name: 'Calgary', records: 68 },
        { name: 'Phoenix', records: 86 },
        { name: 'Philadelphia', records: 94 },
        { name: 'Las Vegas', records: 76 },
        { name: 'Orlando', records: 72 },
        { name: 'San Diego', records: 98 },
        { name: 'Charlotte', records: 66 },
        { name: 'Austin', records: 79 },
        { name: 'San Antonio', records: 74 },
        { name: 'Portland', records: 64 },
        { name: 'Salt Lake City', records: 62 },
        { name: 'Ottawa', records: 61 },
        { name: 'Detroit', records: 67 },
        { name: 'Baltimore', records: 60 },
        { name: 'Nashville', records: 58 },
        { name: 'Kansas City', records: 57 },
        { name: 'Indianapolis', records: 59 },
        { name: 'Minneapolis', records: 63 },
        { name: 'Cleveland', records: 55 },
        { name: 'Edmonton', records: 54 },
        { name: 'Raleigh', records: 52 },
        { name: 'Tampa', records: 51 },
        { name: 'Pittsburgh', records: 50 },
        { name: 'St. Louis', records: 49 },
        { name: 'Cincinnati', records: 48 },
        { name: 'New Orleans', records: 47 },
        { name: 'Buffalo', records: 46 },
        { name: 'Milwaukee', records: 45 },
        { name: 'Oklahoma City', records: 44 },
        { name: 'Louisville', records: 43 },
        { name: 'Richmond', records: 42 },
        { name: 'Columbus', records: 41 },
        { name: 'Quebec City', records: 40 }
      ],
      
      2: [
        { name: 'London', records: 150 },
        { name: 'Berlin', records: 95 },
        { name: 'Paris', records: 110 },
        { name: 'Madrid', records: 105 },
        { name: 'Rome', records: 100 },
        { name: 'Amsterdam', records: 92 },
        { name: 'Vienna', records: 88 },
        { name: 'Brussels', records: 85 },
        { name: 'Lisbon', records: 82 },
        { name: 'Stockholm', records: 80 },
        { name: 'Zurich', records: 78 },
        { name: 'Dublin', records: 75 },
        { name: 'Oslo', records: 73 },
        { name: 'Helsinki', records: 72 },
        { name: 'Copenhagen', records: 74 },
        { name: 'Warsaw', records: 68 },
        { name: 'Budapest', records: 65 },
        { name: 'Prague', records: 67 },
        { name: 'Munich', records: 79 },
        { name: 'Barcelona', records: 83 },
        { name: 'Milan', records: 87 },
        { name: 'Frankfurt', records: 90 },
        { name: 'Hamburg', records: 69 },
        { name: 'Athens', records: 70 },
        { name: 'Manchester', records: 64 },
        { name: 'Bucharest', records: 61 },
        { name: 'Sofia', records: 59 },
        { name: 'Riga', records: 58 },
        { name: 'Vilnius', records: 57 },
        { name: 'Tallinn', records: 55 },
        { name: 'Luxembourg', records: 54 },
        { name: 'Geneva', records: 63 },
        { name: 'Ljubljana', records: 53 },
        { name: 'Zagreb', records: 52 },
        { name: 'Belgrade', records: 51 },
        { name: 'Sarajevo', records: 50 },
        { name: 'Skopje', records: 48 },
        { name: 'Tirana', records: 46 },
        { name: 'Reykjavik', records: 45 },
        { name: 'Krakow', records: 47 },
        { name: 'Seville', records: 49 },
        { name: 'Lyon', records: 44 },
        { name: 'Marseille', records: 43 },
        { name: 'Naples', records: 42 },
        { name: 'Birmingham', records: 41 },
        { name: 'Gothenburg', records: 40 },
        { name: 'Antwerp', records: 39 },
        { name: 'Bergen', records: 38 },
        { name: 'Ghent', records: 37 },
        { name: 'Bratislava', records: 36 }
      ],
      
  };
  
  export const flagUrls = {
    'Brazil': 'https://flagcdn.com/br.svg',
    'Argentina': 'https://flagcdn.com/ar.svg',
    'Peru': 'https://flagcdn.com/pe.svg',
    'Colombia': 'https://flagcdn.com/co.svg',
    'Chile': 'https://flagcdn.com/cl.svg',
    'Venezuela': 'https://flagcdn.com/ve.svg',
    'Ecuador': 'https://flagcdn.com/ec.svg',
    'Uruguay': 'https://flagcdn.com/uy.svg',
    'Paraguay': 'https://flagcdn.com/py.svg',
    'Bolivia': 'https://flagcdn.com/bo.svg',
    
    // North America
    'United States': 'https://flagcdn.com/us.svg',
    'Canada': 'https://flagcdn.com/ca.svg',
    'Mexico': 'https://flagcdn.com/mx.svg',
  
    // Europe
    'United Kingdom': 'https://flagcdn.com/gb.svg',
    'Germany': 'https://flagcdn.com/de.svg',
    'France': 'https://flagcdn.com/fr.svg',
    'Spain': 'https://flagcdn.com/es.svg',
    'Italy': 'https://flagcdn.com/it.svg',
    'Netherlands': 'https://flagcdn.com/nl.svg',
    'Austria': 'https://flagcdn.com/at.svg',
    'Belgium': 'https://flagcdn.com/be.svg',
    'Portugal': 'https://flagcdn.com/pt.svg',
    'Sweden': 'https://flagcdn.com/se.svg',
    'Switzerland': 'https://flagcdn.com/ch.svg',
    'Ireland': 'https://flagcdn.com/ie.svg',
    'Norway': 'https://flagcdn.com/no.svg',
    'Finland': 'https://flagcdn.com/fi.svg',
    'Denmark': 'https://flagcdn.com/dk.svg',
    'Poland': 'https://flagcdn.com/pl.svg',
    'Hungary': 'https://flagcdn.com/hu.svg',
    'Czech Republic': 'https://flagcdn.com/cz.svg',
    'Greece': 'https://flagcdn.com/gr.svg',
    'Romania': 'https://flagcdn.com/ro.svg',
    'Bulgaria': 'https://flagcdn.com/bg.svg',
    'Latvia': 'https://flagcdn.com/lv.svg',
    'Lithuania': 'https://flagcdn.com/lt.svg',
    'Estonia': 'https://flagcdn.com/ee.svg',
    'Luxembourg': 'https://flagcdn.com/lu.svg',
    'Slovenia': 'https://flagcdn.com/si.svg',
    'Croatia': 'https://flagcdn.com/hr.svg',
    'Serbia': 'https://flagcdn.com/rs.svg',
    'Bosnia and Herzegovina': 'https://flagcdn.com/ba.svg',
    'North Macedonia': 'https://flagcdn.com/mk.svg',
    'Albania': 'https://flagcdn.com/al.svg',
    'Iceland': 'https://flagcdn.com/is.svg',
    'Slovakia': 'https://flagcdn.com/sk.svg'
  };
  

  export const locationDetails = {
    'São Paulo': [
            { name: 'Ascenty - Hortolandia HTL1, R. Papa João Paulo II 4, 13185-252 Hortolândia' },
            { name: 'Ascenty - Sao Paulo SP3, Avenida Roberto Pinto Sobrinho, 350, 06268-120 Osasco' },
            { name: 'Ascenty - Paulinia PLN1, R. Sebastião Cardoso 350, 13140-000 Paulínia' },
            { name: 'Ascenty - Sao Paulo SP2, Avenida Roberto Pinto Sobrinho, 350, 06268-120 Osasco' },
            { name: 'Ascenty - Vinhedo VIN1, Av. 2, 50, Quadra G1, Distrito Industrial Benedito Storani, 13288-162 Vinhedo' },
            { name: 'Ascenty - Sao Paulo SP1, Avenida Roberto Pinto Sobrinho, 350, 06268-120 Osasco' },
            { name: 'Ascenty - Sumare SUM2, Rodovia Anhanguera s/n, Parque das Industrias (Nova Veneza), 13177-435 Sumaré' },
            { name: 'Ascenty - Sumare SUM1, Rodovia Anhanguera s/n, Parque das Industrias (Nova Veneza), 13177-435 Sumaré' },
            { name: 'Ascenty - Hortolandia HTL2, Rua Papa João Paulo II, 4, 13185-252 Hortolândia' },
            { name: 'Ascenty - Hortolandia HTL3, Rua Papa João Paulo II, 4, 13185-252 Hortolândia' },
            { name: 'ASAP SP1, Av. das Nações Unidas, 22540, 04795000 São Paulo' },
            { name: 'Equinix SP5x, Av. Marcos Penteado de Ulhôa Rodrigues, 888, 06543-001 Santana de Parnaíba' },
            { name: 'Equinix SP3, Av. Marcos Penteado de Ulhôa Rodrigues, 249, 06543-001 Santana do Parnaíba' },
            { name: 'Ascenty - Campinas CPS1, Avenida Pierre Simon de Laplace, 1211, 13069-320 Campinas' },
            { name: 'Equinix SP4, Av. Ceci, 1900 - Res. Tambore, Tamboré, 06460-120 Barueri' },
            { name: 'SBA Edge Sao Paulo, Rua Jose Abrantes, 186, 04756-010 Sao Paulo' },
            { name: 'Equinix SP1, Rua Doutor Miguel Couto, 58, Centro, 01008-010 São Paulo' },
            { name: 'Novvacore Data Center, Rua Professor Filadelfo de Azevedo 712, 04508011 Sao Paulo' },
            { name: 'Elea Digital SPO1, Av. Guido Caloi 1000, 05802 Sao Paulo' },
            { name: 'Ascenty - Jundiai JDI1, Rua Presbítero Plínio Alves de Souza, 757, 13212-181 Jundiaí' },
            { name: 'Scala Data Centers SGRUSP02, Alameda Glete 700, 01215 Sao Paulo' },
            { name: 'Vivo São Paulo - Guarulhos Data Center, Rua Doutor Timóteo Penteado, 976, 07094-000 Guarulhos' },
            { name: 'Cirion SAO1, Av. Eid Mansur, 666, 06708-070 Parque Sao Georgia Cotia' },
            { name: 'Ascenty - Sao Paulo SP4, Avenida Roberto Pinto Sobrinho, 350, 06276-016 Osasco' },
            { name: 'Ascenty - Jundiai JDI2, Av. Beirute, 863, 13212-181 Jundiaí' },
            { name: 'Ascenty - Sao Paulo SP5, Avenida Roberto Pinto Sobrinho, 350, 06268-120 Osasco' },
            { name: 'Ascenty - Sao Paulo SP6, Av. Roberto Pinto Sobrinho, 350, 06268-120 Osasco' },
            { name: 'NextStream Tamboré, Av. Marcos Penteado de Ulhôa Rodrigues, 06543-001 Santana de Parnaíba' },
            { name: 'TAKDOA Sao Paulo - SP1, R. Bento Branco de Andrade Filho, 621 - Jardim Dom Bosco, 04757-000 São Paulo' },
            { name: 'Equinix SP2, Alameda Araguaia, 3641 Tamboré, 06455-000 Barueri' },
            { name: 'Vivo Tamboré 1 Data Center, Av. Marcos Penteado de Ulhôa Rodrigues, 1690, 06543-001 Santana de Parnaíba' },
            { name: 'IPXON Sao Paulo, Avenida Roberto Pinto Sobrinho, 350, 06276-125 Osasco' },
            { name: 'PIX G8 Sao Paulo, Rua Florida, 1738, 04565-001 Sao Paulo' },
            { name: 'Aligned SP-02, R. José Blumer, 150, 13186-510 Chácaras Assay, Hortolândia' },
            { name: 'Scala Data Centers SVCPJD02, Rod. Vice Pref. Hermenegildo Tonoli, 13212-365 Jundiaí' },
            { name: 'Elea Digital SPO3, Al. Rio Negro, 530, 06454-000 Barueri' },
            { name: 'Elea Digital SPO2, Av. Marginal Direita Anchieta, 1241, 09891-420 São Bernardo do Campo' },
            { name: 'ADA Sao Paulo, Av. Brig. Faria Lima, 3930, 04538-132 Sao Paulo' },
            { name: 'TAKDOA Sao Paulo - SP2, Av. Maria Coelho Aguiar, 215 - Jardim Sao Luis, 05805-000 São Paulo' },
            { name: 'B3 Data Center, R. Ricardo Prudente de Aquino, 85 - Res. Tambore III, 06543-004 Santana de Parnaiba' },
            { name: 'Microsoft Sao Paulo, Rua Santa Teresa, 64, 01016-020 Sao Paulo' },
            { name: 'Equinix SP6, Av. Cid Viêira da Souza, 460-484, 06544 Santana de Parnaíba' },
            { name: 'Aligned SP-01, 39,2, Estr. dos Romeiros, 943, 06513-001 Votuparim, Santana de Parnaíba' },
            { name: 'Maxihost, Rua Dr. Eduardo Martinelli, 100, 04013050 Sao Paulo' },
            { name: 'Telium Data Center - SPO, Av. das Nações Unidas, 13797, 04794000 São Paulo' },
            { name: 'Aligned SP-03, Alameda Araguacema, 187, 06460-070 Tamboré, Barueri' },
            { name: 'QNAX Data Center, Av. Nossa Sra do Ó, 865, 02715-000 Limão' },
            { name: 'Ultranet Telecom, Rua Simao Dias da Fonseca, 61, 01539-020 Cambuci' },
            { name: 'Connect Web, Av. das Nações Unidas, 12995 - 10º andar, 04578-000 São Paulo' },
            { name: 'Insidesign_Ribeirao, Av. Saudade 1210 sala 325, 14085-000 Ribeirao Preto' },
            { name: 'cdznet data center, rua independencia, 2472, 15025095 Sao Jose do Rio Preto' },
            { name: 'Datacenter Locaweb Itapaiuna, Rua Itapaiuna, 2434, 05707-001 Sao Paulo' },
            { name: 'Datacenter Locaweb JK, Av. Presidente Juscelino Kubitscheck, 1830 1º Andar, 04543-900 São Paulo' },
            { name: 'Glete, UOLDIVEO, Alameda Glete, 700, 01215-001 São Paulo' },
            { name: 'Tamboré, UOLDIVEO, Av. Ceci, 1850, 06460-120 São Paulo' }          
    ],
    'Mexico City': [{ name: 'Additional 3' }, { name: 'Additional 4' }],
  };